### ISSUE TITLE
orderBy not working and orderby gives http 500 error

### ISSUE THREAD

**Issue by jolySoft** [beyond-code-github/LinqToQuerystring#37]
if I apply a $orderBy=Name, for example and check EF Profiler this is not being applied to the Sql.

Also if I use it lower case (i.e. $orderby=Name) I get the following error:
ExceptionMessage=No method 'get_Item' exists on type xxx.

**Comment by automada** [comment]
Just a comment here for future reference. I got the same error using $orderby=[Name], but it works with $orderby=Name. ForceDynamicProperties is not set. 
Based on the examples, I'm not quite sure when to use the square brackets or not.
